# Generated by Django 5.1 on 2024-08-11 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='personel',
            name='user',
        ),
        migrations.AddField(
            model_name='material',
            name='quantity_units',
            field=models.CharField(default='KG', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='expected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='revenue_unit',
            field=models.CharField(default='KES', max_length=10),
        ),
        migrations.AddField(
            model_name='personel',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personel', to='project_manager.employee'),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('distance', models.CharField(max_length=250)),
                ('distance_units', models.CharField(default='KM', max_length=10)),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='milestone', to='project_manager.project')),
            ],
        ),
    ]
