# Generated by Django 5.0.7 on 2024-07-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_milestone_project_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='quantity_units',
            field=models.CharField(default='KG', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='revenue_unit',
            field=models.CharField(default='KES', max_length=10),
        ),
    ]
