# Generated by Django 5.1 on 2024-08-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_employee_remove_personel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personel',
            name='role',
        ),
        migrations.AlterField(
            model_name='personel',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=True, null=True),
        ),
    ]
