# Generated by Django 5.0.7 on 2024-07-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_material_quantity_units_project_revenue_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='revenue',
            new_name='expected_revenue',
        ),
    ]
