# Generated by Django 5.1 on 2024-08-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='revenue_unit',
            field=models.CharField(default='$', max_length=10),
        ),
    ]
