# Generated by Django 5.1 on 2024-08-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_alter_project_revenue_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personel',
            new_name='Personnel',
        ),
    ]
