# Generated by Django 5.1 on 2024-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_rename_personel_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cost_unit',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='machinery',
            name='cost_unit',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='cost_unit',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_unit',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
